################################################################################
#
# This is the conifguration file for the front end project
#
# @author Jack <jack@thinkingcloud.info>
# @version 0.0.1
# @date Thu Feb 22 15:28:14 2018
#
################################################################################

#===============================================================================
#
# Include the values in package.json
#
#===============================================================================

#json ./package.json

#===============================================================================
#
# Section Templates
#
#===============================================================================


#===============================================================================
#
# Section Webpack
#
#===============================================================================
webpack:
    entry: # The entry settings
        bundle: index.js
    output: # The output settings
        path: $(__dir)/dist
        filename: "[name].js"
    resolve:
        modules: 
            - $(__dir)/src
        extensions: 
            - .js
            - .jsx
    plugins:
        -
            $type: module
            $module: webpack
            $name: DefinePlugin
            test: 123
    ^module/rules:
        -
            @test: \.js(x)?$
            @exclude: node_modules
            include: $(__dir)/src
            use:
                # We will make the routing generation to the top
                -
                    loader: ./webpack/route
                    options:
                        routerAccessor:
                            $type: function
                            $module: ./projects/backend/main/src/functions.js
                            $name: get_routes
                -
                    loader: babel-loader
                    options:
                        presets:
                            - react
                        cacheDirectory: true
