################################################################################
#
# This is the configuration file for routing
#
# @author Jack <jack@thinkingcloud.info>
# @version 0.0.1
# @date Wed Feb  7 10:33:30 2018
#
################################################################################

#===============================================================================
#
# Template Section
#
#===============================================================================

route-templates:
    abstract-filter: &abstract-filter
        $type: function
        $module: ./models
    abstract-route: &abstract-route
        $reload: true # This will indicate the module should be loaded using with the reload support
        filters:
            -
                $base: *abstract-filter
                $name: logRequest
    routes-template: &base-routes
        $type: module
        $module: ./models
        $name: Routes
        $router:
            mergeParams: true
    base-react-route-template: &base-react-route
        $type: module
        $module: ./models
        $name: ReactRoute
    base-route-template: &base-route
        $base: *abstract-route
        $type: function
        $module: ./models
    redirect-route-template: &redirect-route
        $base: *abstract-route
        $type: module
        $module: ./models
        $name: RedirectRoute

#===============================================================================
#
# Elements Section
#
#===============================================================================
elements:
    dashboard-ui: &dashboard-ui # The UI element is used for identify the ui element of this route, the UI element will indicate the routing configuration for the fronend
        $type: module
        $module: ./models
        $name: ReactUI
        entry: main.js # This is the entry file, mostly it is used for webpack, so if you don't have webpack, you can leave this as blank
        js: # This is the configuration for other js files that are needed
            #ifenv DEV_SERVER
            - hotload.js
            #else
            - share.js
            - vendor.js
            - main.js
        css:
            - share.css
            #endif

#===============================================================================
#
# Routes Section
#
#===============================================================================

route_config:
    $base: *base-routes
    root: / # This is required, so that the router can know its service request, this context can allow multiple server module run at the same express server
    routes:
        /: # The root route will redirect to dashboard
            $base: *redirect-route
            to: /dashboard
        /test: 
            $base: *base-route
            $name: test
        /dashboard:
            $base: *base-routes
            routes:
                /:
                    $base: *base-route
                    $name: dashboard
                    $ui: 
                        $base: *base-react-route
                        element: *dashboard-ui
                        attrs:
                            - requireAuth
                            - exact
                        ^component/module: dashboard/dashboard.component
                /demo:
                    $base: *base-route
                    $name: dashboardDemo
                    $ui: 
                        $base: *base-react-route
                        element: *dashboard-ui
                        attrs:
                            - requireAuth
                            - exact
                        ^component/module: dashboard/dashboard.component.demo
    handlers:
        404:
            $base: *base-route
            $name: notFound
        500:
            $base: *base-route
            $name: serverError
